import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextProviders from "./NextProviders";
import SideMenu from "@/components/SideMenu";
import ScreenWidth from "@/components/screen-width";
import { bgStyle, textStyle } from "@/lib/twStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <NextProviders
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className={`flex  h-screen min-h-screen ${bgStyle} ${textStyle} `}
          >
            {children}
          </div>
          <ScreenWidth />
        </NextProviders>
      </body>
    </html>
  );
}
